apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8070"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-12-27T09:47:54Z"
  generateName: contrail-vrouter-masters-
  labels:
    app: contrail-vrouter-masters
    controller-revision-hash: 5cc9f874d
    pod-template-generation: "1"
  name: contrail-vrouter-masters-2cvsj
  namespace: contrail
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: contrail-vrouter-masters
    uid: bbd8165c-53a1-429a-8260-61d7354b0af6
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - sharmag-k8s-master-pnad30.englab.juniper.net
  containers:
  - command:
    - /vrouter-supervisor
    env:
    - name: PODIP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: GATEWAY
    - name: AGENTMODETYPE
      value: dpdk
    - name: DATACONTROLINTERFACE
      value: enp3s0
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-agent:master
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /vrouter-health-check
        port: 9091
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
    name: contrail-vrouter-agent
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    startupProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /vrouter-health-check
        port: 9091
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/lib/contrail
      name: var-lib-contrail
    - mountPath: /var/run
      name: var-run
    - mountPath: /var/run/contrail
      name: var-run-contrail
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /var/crash
      name: var-crashes
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /dev
      name: dev
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnnnf
      readOnly: true
  - command:
    - /dpdk-supervisor
    env:
    - name: INTERFACE_LAYER
      value: l3
    - name: RESTORE_INTERFACES
      value: "false"
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    envFrom:
    - configMapRef:
        name: contrail-vrouter-masters-env-configmap
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-dpdk:master
    imagePullPolicy: IfNotPresent
    name: contrail-vrouter-agent-dpdk
    resources:
      limits:
        hugepages-1Gi: 6Gi
        memory: 6Gi
      requests:
        hugepages-1Gi: 6Gi
        memory: 6Gi
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev
      name: dev
    - mountPath: /var/lib/kubelet
      name: var-lib-kubelet
    - mountPath: /var/lib/contrail
      name: var-lib-contrail
    - mountPath: /dev/hugepages
      name: hugepages
    - mountPath: /var/run
      name: docker-unix-socket
    - mountPath: /etc/sysconfig/network-scripts
      name: network-scripts
    - mountPath: /host/bin
      name: host-bin
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /usr/src
      name: usr-src
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /var/crash
      name: var-crashes
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnnnf
      readOnly: true
  - command:
    - /telemetry-exporter
    - run
    - -c
    - /etc/telemetry-exporter/config/config-vrouter.yaml
    env:
    - name: TELEMETRY_EXPORTER_SCHEME
      value: http
    - name: INTROSPECT_SCHEME
      value: http
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: TYPE
      value: vrouter
    - name: NAMESPACE
      value: contrail
    - name: INTROSPECT_SCHEME
      value: http
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master
    imagePullPolicy: IfNotPresent
    name: contrail-vrouter-telemetry-exporter
    ports:
    - containerPort: 8070
      hostPort: 8070
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /testing
      name: telemetry-exporter-overrides
    - mountPath: /etc/config/metrics-collector
      name: metrics-collector
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /etc/config/metrics/tls
      name: telemetry-exporter-tls
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnnnf
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - args:
    - sysctl -w net.ipv6.conf.default.addr_gen_mode=0 && sysctl -w net.ipv6.conf.all.addr_gen_mode=0
      && sysctl -w net.ipv6.conf.default.autoconf=0 && sysctl -w net.ipv6.conf.all.autoconf=0
      && echo -e "\nSuccessfully loaded kernel parameter using sysctl cli\n" || echo
      -e "\nError in loading kernel parameter using sysctl cli\n"; modprobe tun &&
      modprobe ipip && modprobe ip_tunnel && modprobe ip6_tunnel && modprobe mpls_gso
      && modprobe mpls_router && modprobe mpls_iptunnel && modprobe vrf && modprobe
      vxlan && modprobe fou && modprobe fou6 && echo -e "\nSuccessfully loaded kernel
      modules\n" || echo -e "Error in loadinfg kernel modules. Check whether kernel
      modules packages are installed or not.\nIf running OS is Ubuntu, Run following
      command and reboot  to enable kernel modules.\nsudo apt install linux-generic
      -y \n sudo apt install --reinstall linux-image-$(uname -r) -y; \n sudo apt install
      --reinstall linux-modules-$(uname -r) -y;\n sudo apt install --reinstall linux-modules-extra-$(uname
      -r) -y; \n" ; set -o pipefail && python3 -u crpdconfig_generator/crpdconfig_generator.py
      evpn | tee -a "/var/log/contrail/cleanup.log";
    command:
    - /bin/sh
    - -c
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: PYTHONUNBUFFERED
      value: "1"
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21
    imagePullPolicy: IfNotPresent
    name: jcnr-evpn-conf
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /var/lib/contrail
      name: var-lib-contrail
    - mountPath: /var/run
      name: var-run
    - mountPath: /var/run/contrail
      name: var-run-contrail
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /var/crash
      name: var-crashes
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnnnf
      readOnly: true
  - command:
    - /contrail-init
    - -service
    - vrouter
    env:
    - name: PODIP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: NAMESPACE
      value: contrail
    - name: DATACONTROLINTERFACE
      value: enp3s0
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-init:master
    imagePullPolicy: IfNotPresent
    name: contrail-init
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
    - mountPath: /etc/contrail
      name: config-volume
    - mountPath: /var/run
      name: var-run
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /etc/contrail/dynamic-config
      name: dynamic-config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnnnf
      readOnly: true
  - command:
    - /vrouter-go
    - /vrouter-go
    env:
    - name: PODNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    envFrom:
    - configMapRef:
        name: contrail-vrouter-masters-env-configmap
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-kernel-init-dpdk:master
    imagePullPolicy: IfNotPresent
    name: contrail-vrouter-kernel-init-dpdk
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
        - NET_ADMIN
        - SYS_PTRACE
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/src
      name: usr-src
    - mountPath: /lib/modules
      name: lib-modules
    - mountPath: /etc/sysconfig/network-scripts
      name: network-scripts
    - mountPath: /host/bin
      name: host-bin
    - mountPath: /var/run
      name: docker-unix-socket
    - mountPath: /host/etc/contrail
      name: etc-contrail
    - mountPath: /var/log/contrail
      name: var-log-contrail
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rnnnf
      readOnly: true
  nodeName: sharmag-k8s-master-pnad30.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsUser: 1000
  serviceAccount: contrail-serviceaccount
  serviceAccountName: contrail-serviceaccount
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: lables
    name: podinfo
  - emptyDir: {}
    name: config-volume
  - configMap:
      defaultMode: 420
      name: dynamic-config-configmap
    name: dynamic-config-volume
  - configMap:
      defaultMode: 420
      name: contrail-vrouter-masters-cni-configmap
    name: cni-config-volume
  - hostPath:
      path: /var/lib/kubelet
      type: ""
    name: var-lib-kubelet
  - hostPath:
      path: /var/lib/contrail
      type: ""
    name: var-lib-contrail
  - hostPath:
      path: /var/run/contrail
      type: ""
    name: var-run-contrail
  - hostPath:
      path: /var/crash
      type: ""
    name: var-crashes
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: main-cni-bin
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: main-cni-conf
  - hostPath:
      path: /var/run
      type: ""
    name: var-run
  - hostPath:
      path: /var/log/jcnr/
      type: DirectoryOrCreate
    name: var-log-contrail
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - hostPath:
      path: /sys
      type: ""
    name: sys
  - hostPath:
      path: /etc
      type: ""
    name: etc
  - configMap:
      defaultMode: 420
      name: telemetry-exporter-overrides-configmap
      optional: true
    name: telemetry-exporter-overrides
  - configMap:
      defaultMode: 420
      name: metrics-collector-configmap
      optional: true
    name: metrics-collector
  - name: telemetry-exporter-tls
    secret:
      defaultMode: 420
      optional: true
      secretName: telemetry-exporter-tls
  - hostPath:
      path: /dev
      type: ""
    name: dev
  - hostPath:
      path: /etc/contrail
      type: ""
    name: etc-contrail
  - hostPath:
      path: /var/run
      type: ""
    name: docker-unix-socket
  - hostPath:
      path: /usr/src
      type: ""
    name: usr-src
  - hostPath:
      path: /dev/hugepages
      type: ""
    name: hugepages
  - hostPath:
      path: /etc/sysconfig/network-scripts
      type: ""
    name: network-scripts
  - hostPath:
      path: /bin
      type: ""
    name: host-bin
  - name: kube-api-access-rnnnf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:48:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:48:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:48:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://b4230889c59e447ed33bca7ace5d8b71b6427b18fc5a8c1cd509e77f366a2035
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-agent:master
    imageID: 5e3c0b5487aee28e3b1e4edf172558f96e5bb6586a5c6c929884ebae362e2178
    lastState: {}
    name: contrail-vrouter-agent
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-27T09:48:13Z"
  - containerID: cri-o://6b9237aac217c5ee4f6d77a8e2847090f3cd784eaaf48b38036ab666a68945ee
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-dpdk:master
    imageID: e4ec475a2212097a3f883b5d222615c2f99f98bf0b197d3e6a50f5a0d7154a19
    lastState: {}
    name: contrail-vrouter-agent-dpdk
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-27T09:48:15Z"
  - containerID: cri-o://3947f18904bc524edcdc3ffc5b519f429ea25ab7a30cfd11f1cf4327afddac2f
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:master
    imageID: 74442f1336697f386f1f32c0f2fe3859643fd397cf29919b151ee74c269a2a4c
    lastState: {}
    name: contrail-vrouter-telemetry-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-27T09:48:17Z"
  hostIP: 192.168.1.2
  initContainerStatuses:
  - containerID: cri-o://844dd5123aeb8102dced3b7d5196cd78b1d756d3a822eebe2e04a99b849ec746
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpdconfig-generator:v21
    imageID: b0804dda66d833cb2e4b2847807b0ccb1ec1f87c467c20e9779bbc3f088c493b
    lastState: {}
    name: jcnr-evpn-conf
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://844dd5123aeb8102dced3b7d5196cd78b1d756d3a822eebe2e04a99b849ec746
        exitCode: 0
        finishedAt: "2023-12-27T09:47:55Z"
        reason: Completed
        startedAt: "2023-12-27T09:47:55Z"
  - containerID: cri-o://1b2a490dfe9e502bfc16d71bbe9731cebd1ceb56e8ac73b09bf3062e77b1dbab
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-init:master
    imageID: 2f84ae1e04f7e298290113ffea34dc0f84dfb56b35880c0b8e120fd2d8c005e2
    lastState: {}
    name: contrail-init
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://1b2a490dfe9e502bfc16d71bbe9731cebd1ceb56e8ac73b09bf3062e77b1dbab
        exitCode: 0
        finishedAt: "2023-12-27T09:47:58Z"
        reason: Completed
        startedAt: "2023-12-27T09:47:58Z"
  - containerID: cri-o://8033f0d9510f17d9868ca6c1433f3faa7b242d07302f07a6d1f76a7d420f1f24
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-kernel-init-dpdk:master
    imageID: a9e146057dcf7899d0e6423356ca2a212e22a0c10a661b47d403da07493c84b9
    lastState: {}
    name: contrail-vrouter-kernel-init-dpdk
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://8033f0d9510f17d9868ca6c1433f3faa7b242d07302f07a6d1f76a7d420f1f24
        exitCode: 0
        finishedAt: "2023-12-27T09:48:00Z"
        reason: Completed
        startedAt: "2023-12-27T09:48:00Z"
  phase: Running
  podIP: 192.168.1.2
  podIPs:
  - ip: 192.168.1.2
  qosClass: Burstable
  startTime: "2023-12-27T09:47:54Z"
