apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"gitea-service","namespace":"default"},"spec":{"ports":[{"nodePort":30033,"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"gitea"},"type":"NodePort"}}
  creationTimestamp: "2024-01-30T10:20:44Z"
  name: gitea-service
  namespace: default
spec:
  clusterIP: 10.10.10.224
  clusterIPs:
  - 10.10.10.224
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30033
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
